name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run Newman Collection
        run: newman run postman/collections/collection_test_01.json -r htmlextra--reporter-htmlextra-export SampleArtifact/newman-report.html

      - name: Upload Newman Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Publish 
        uses: actions/upload-artifact@v3
        with: 
          name: Reports
          path: SampleArtifact
